version: '3.7'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: fake-db
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./log:/var/log/mysql
    ports:
      - "127.0.0.1:33060:3306"

volumes:
  db: